package com.servers.ozzbzk;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class string {
        public static final int app_name = 0x7f010000;
    }

    public static final class xml {
        public static final int device_admin = 0x7f020000;
    }
}
